######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 13 17:57:56 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui